spring:
  application:
    name: SpringFrameworkLesson5.SpringDataForWorkingWithDatabases
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

