
server:
  port: 8765


spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: tasks
          uri: http://localhost:8081/
          predicates:
            - Path=/task/**
