global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'tasks'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: 'eureka'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8761']

